import io
from io import BytesIO
from markdown_it import MarkdownIt
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib import colors
import matplotlib.pyplot as plt
import re
import base64
from PIL import Image as PILImage

# Colors from Curious Horizons Design Language
NEBULA_GOLD = colors.HexColor("#dcb44e")
COSMIC_BLUE = colors.HexColor("#1e3a8a")
GLASS_BG = colors.HexColor("#f8fafc")
TEXT_MAIN = colors.HexColor("#111827")
TEXT_MUTED = colors.HexColor("#6b7280")
TEXT_LIGHT = colors.HexColor("#9ca3af")

# Enable tables plugin for markdown parsing
md = MarkdownIt("commonmark").enable('table')
plt.switch_backend('Agg')

def render_math_to_image(latex_str, is_display=False):
    fig = plt.figure(figsize=(0.01, 0.01))
    fontsize = 16 if is_display else 12
    try:
        fig.text(0, 0, f"${latex_str}$", fontsize=fontsize)
        buf = BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', pad_inches=0.05, dpi=150, transparent=True)
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception as e:
        print("Failed to render math:", latex_str, e)
        plt.close(fig)
        return None

def extract_math(text):
    parts = []
    pattern = r'(\$\$[^\$]+\$\$|\$[^\$]+\$)'
    tokens = re.split(pattern, text)
    for token in tokens:
        if token.startswith('$$') and token.endswith('$$'):
            parts.append(('display_math', token[2:-2]))
        elif token.startswith('$') and token.endswith('$'):
            parts.append(('inline_math', token[1:-1]))
        else:
            if token:
                parts.append(('text', token))
    return parts

def header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('Helvetica-Bold', 10)
    canvas.setFillColor(NEBULA_GOLD)
    canvas.drawString(doc.leftMargin, doc.pagesize[1] - 0.5 * inch, "Curious Horizons")
    
    # Header Divider
    canvas.setStrokeColor(COSMIC_BLUE)
    canvas.setLineWidth(0.5)
    canvas.line(doc.leftMargin, doc.pagesize[1] - 0.55 * inch, doc.pagesize[0] - doc.rightMargin, doc.pagesize[1] - 0.55 * inch)
    
    # Footer Divider
    canvas.line(doc.leftMargin, 0.65 * inch, doc.pagesize[0] - doc.rightMargin, 0.65 * inch)
    
    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(doc.leftMargin, 0.45 * inch, "Generated by Curious Horizons")
    
    # Page Number
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.45 * inch, f"{doc.page}")
    
    canvas.restoreState()

def create_pdf_from_markdown(markdown_text, topic_name="Generated Notes", document_type="PDF Notes"):
    pdf_buffer = BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=1 * inch,
        leftMargin=1 * inch,
        topMargin=1.2 * inch,
        bottomMargin=1.2 * inch
    )
    
    styles = getSampleStyleSheet()
    
    # Base Styles with Consistent Spacing and Hierarchy
    styles.add(ParagraphStyle(name='CustomNormal', parent=styles['Normal'], fontSize=11, leading=17, spaceBefore=6, spaceAfter=10, textColor=TEXT_MAIN))
    styles.add(ParagraphStyle(name='CustomHeading1', parent=styles['Heading1'], fontSize=22, leading=26, spaceBefore=24, spaceAfter=14, keepWithNext=True, textColor=NEBULA_GOLD))
    styles.add(ParagraphStyle(name='CustomHeading2', parent=styles['Heading2'], fontSize=16, leading=20, spaceBefore=18, spaceAfter=12, keepWithNext=True, textColor=COSMIC_BLUE))
    styles.add(ParagraphStyle(name='CustomHeading3', parent=styles['Heading3'], fontSize=13, leading=18, spaceBefore=14, spaceAfter=8, keepWithNext=True, textColor=TEXT_MAIN, fontName='Helvetica-Bold'))
    
    # Title Page Styles
    styles.add(ParagraphStyle(name='TitleTopic', parent=styles['Normal'], fontSize=36, leading=42, spaceAfter=16, textColor=NEBULA_GOLD, fontName='Helvetica-Bold', alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='TitleType', parent=styles['Normal'], fontSize=18, leading=22, spaceAfter=32, textColor=TEXT_LIGHT, fontName='Helvetica', alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='TitleGen', parent=styles['Normal'], fontSize=12, leading=16, spaceAfter=48, textColor=TEXT_MUTED, fontName='Helvetica', alignment=TA_CENTER))
    
    flowables = []
    
    # Premium Cover Page
    from reportlab.platypus import PageBreak
    flowables.append(Spacer(1, 2.5 * inch))
    flowables.append(Paragraph(topic_name, styles['TitleTopic']))
    flowables.append(Paragraph(document_type, styles['TitleType']))
    flowables.append(Spacer(1, 0.5 * inch))
    flowables.append(Paragraph("Curious Horizons", styles['TitleGen']))
    flowables.append(PageBreak())
    
    tokens = md.parse(markdown_text)
    
    class RenderState:
        def __init__(self):
            self.list_items = []
            self.in_list = False
            self.table_data = []
            self.in_table = False
            self.row_data = []
            self.buffering_component = False
            self.component_flowables = []
            self.component_colors = (GLASS_BG, COSMIC_BLUE)
            self.seen_headings = set()
            self.skipping = False
            self.temp_files = []

    state = RenderState()
    
    def append_flowable(f):
        if type(f) is list:
            if state.buffering_component:
                state.component_flowables.extend(f)
            else:
                flowables.extend(f)
        else:
            if state.buffering_component:
                state.component_flowables.append(f)
            else:
                flowables.append(f)

    def flush_component():
        if state.buffering_component and state.component_flowables:
            bg_color, border_color = state.component_colors
            # Table width slightly smaller than page width for better margins
            t = Table([[state.component_flowables]], colWidths=[doc.width - 24])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), bg_color),
                ('BOX', (0,0), (-1,-1), 1, border_color),
                ('TOPPADDING', (0,0), (-1,-1), 16),
                ('BOTTOMPADDING', (0,0), (-1,-1), 16),
                ('LEFTPADDING', (0,0), (-1,-1), 24),
                ('RIGHTPADDING', (0,0), (-1,-1), 24),
            ]))
            flowables.append(t)
            flowables.append(Spacer(1, 18))
        state.buffering_component = False
        state.component_flowables = []
        state.component_colors = (GLASS_BG, COSMIC_BLUE)

    def is_component_heading(text):
        text = text.lower()
        return any(k in text for k in [
            'formula', 'equation', 'exam trap', 'mistake', 'memory', 
            'trick', 'quick revision', 'checklist', 'important note', 
            'quick tip', 'one-line definition', 'three things'
        ])

    def get_component_colors(heading_text):
        text = heading_text.lower()
        if 'formula' in text or 'equation' in text:
            return colors.HexColor("#f0fdfa"), colors.HexColor("#0d9488") # Teal
        if 'exam trap' in text or 'mistake' in text:
            return colors.HexColor("#fef2f2"), colors.HexColor("#ef4444") # Red
        if 'memory' in text or 'trick' in text:
            return colors.HexColor("#fdf4ff"), colors.HexColor("#c026d3") # Fuchsia
        return GLASS_BG, COSMIC_BLUE

    def process_inline_tokens(token):
        if not token.children:
            return token.content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        xml = ""
        for child in token.children:
            if child.type == 'text':
                xml += child.content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            elif child.type == 'strong_open':
                xml += "<b>"
            elif child.type == 'strong_close':
                xml += "</b>"
            elif child.type == 'em_open':
                xml += "<i>"
            elif child.type == 'em_close':
                xml += "</i>"
            elif child.type == 'code_inline':
                xml += f"<font name='Courier'>{child.content}</font>"
            elif child.type == 'softbreak':
                xml += " "
            elif child.type == 'hardbreak':
                xml += "<br/>"
            elif child.type == 'html_inline':
                xml += child.content
            elif child.type == 'image':
                src = child.attrs.get('src', '')
                alt = child.content
                xml += f'<img src="{src}" alt="{alt}"/>'
        return xml

    def split_xml_and_images(xml_text, style):
        result_flowables = []
        current_xml = ""
        open_tags = []
        
        # Match ANY base64 image
        pattern = re.compile(r'(<img\s+[^>]*src=["\']data:image/[^>]+>)')
        
        parts = pattern.split(xml_text)
        for part in parts:
            if part.startswith('<img') and 'data:image/' in part:
                try:
                    src_match = re.search(r'src=["\']data:image/([a-zA-Z0-9]+);base64,([^"\']+)["\']', part)
                    if not src_match:
                        raise ValueError("Could not parse data URI")
                        
                    img_type, b64_data = src_match.groups()
                    img_bytes = base64.b64decode(b64_data)
                    img_io = BytesIO(img_bytes)
                    
                    width_match = re.search(r'width=["\']([0-9\.]+)["\']', part)
                    height_match = re.search(r'height=["\']([0-9\.]+)["\']', part)
                    
                    pil_img = PILImage.open(img_io)
                    orig_w, orig_h = pil_img.size
                    img_io.seek(0)
                    
                    w_pt = float(width_match.group(1)) if width_match else orig_w * 0.75
                    h_pt = float(height_match.group(1)) if height_match else orig_h * 0.75
                    
                    # Prevent Formula Overflow: scale down if it exceeds page width
                    max_width = 400 # A4 width minus margins is ~450, 400 is very safe
                    if w_pt > max_width:
                        scale = max_width / w_pt
                        w_pt *= scale
                        h_pt *= scale
                    
                    img_flowable = Image(img_io, width=w_pt, height=h_pt)
                    img_flowable.hAlign = 'CENTER'
                    
                    if current_xml.strip():
                        closed_xml = current_xml
                        for tag in reversed(open_tags):
                            tag_name = tag.split()[0]
                            closed_xml += f"</{tag_name}>"
                        result_flowables.append(Paragraph(closed_xml, style))
                        current_xml = ""
                        for tag in open_tags:
                            if tag == 'b': current_xml += "<b>"
                            elif tag == 'i': current_xml += "<i>"
                            elif tag.startswith('font'): current_xml += f"<{tag}>"
                    
                    result_flowables.append(img_flowable)
                except Exception as e:
                    print("Skipping malformed base64 image:", e)
                    current_xml += "[Diagram]"
            else:
                tag_pattern = re.compile(r'(</?(?:b|i|font)[^>]*>)')
                subparts = tag_pattern.split(part)
                for sub in subparts:
                    if sub.startswith('<') and sub.endswith('>'):
                        if sub.startswith('</'):
                            tag_name = sub[2:-1].split()[0]
                            if open_tags and open_tags[-1].startswith(tag_name):
                                open_tags.pop()
                        elif not sub.endswith('/>'):
                            tag_name = sub[1:-1]
                            open_tags.append(tag_name)
                    current_xml += sub

        if current_xml.strip():
            closed_xml = current_xml
            for tag in reversed(open_tags):
                tag_name = tag.split()[0]
                closed_xml += f"</{tag_name}>"
            result_flowables.append(Paragraph(closed_xml, style))
            
        return result_flowables

    def handle_text_with_math(xml_text, style):
        parts = extract_math(xml_text)
        if len(parts) == 1 and parts[0][0] == 'text':
            return split_xml_and_images(parts[0][1], style)
            
        import base64
        from PIL import Image as PILImage
        
        paragraph_xml = ""
        for p_type, content in parts:
            if p_type == 'text':
                paragraph_xml += content
            elif p_type == 'inline_math':
                buf = render_math_to_image(content, is_display=False)
                if buf:
                    import tempfile
                    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
                    tmp_file.write(buf.getvalue())
                    tmp_file.close()
                    tmp_path = tmp_file.name
                    state.temp_files.append(tmp_path)
                    
                    with PILImage.open(tmp_path) as pil_img:
                        w, h = pil_img.size
                    # Scale down inline math slightly so it fits line height better
                    w_pt = w * 0.65
                    h_pt = h * 0.65
                    # Inline math uses a real file path so ReportLab Paragraph can read it directly
                    paragraph_xml += f'<img src="{tmp_path}" width="{w_pt}" height="{h_pt}" valign="middle"/>'
                else:
                    paragraph_xml += f"${content}$"
            elif p_type == 'display_math':
                buf = render_math_to_image(content, is_display=True)
                if buf:
                    img_b64 = base64.b64encode(buf.read()).decode('utf-8')
                    buf.seek(0)
                    with PILImage.open(buf) as pil_img:
                        w, h = pil_img.size
                    w_pt = w * 0.75
                    h_pt = h * 0.75
                    # Display math gets extracted into a centered Image flowable
                    paragraph_xml += f'<img src="data:image/png;base64,{img_b64}" width="{w_pt}" height="{h_pt}"/>'
                else:
                    paragraph_xml += f"<br/>$${content}$$<br/>"
        
        return split_xml_and_images(paragraph_xml, style)

    i = 0
    while i < len(tokens):
        tok = tokens[i]
        
        if state.skipping:
            if tok.type == 'heading_open' and int(tok.tag[1]) <= 2:
                # We reached the next major section, stop skipping
                state.skipping = False
            else:
                i += 1
                continue
                
        if tok.type == 'heading_open':
            level = int(tok.tag[1])
            if level <= 2:
                flush_component()
                
            style_name = f'CustomHeading{level}' if level <= 3 else 'CustomHeading3'
            i += 1
            inline_tok = tokens[i]
            text = process_inline_tokens(inline_tok)
            
            # Prevent Duplicated Sections by tracking H1 and H2 headings
            if level <= 2:
                heading_key = text.lower().strip()
                if heading_key in state.seen_headings:
                    state.skipping = True
                    i += 1
                    continue
                else:
                    state.seen_headings.add(heading_key)
            
            heading_flowables = handle_text_with_math(text, styles[style_name])
            
            if level == 2 and is_component_heading(text):
                state.buffering_component = True
                state.component_colors = get_component_colors(text)
                append_flowable(heading_flowables)
            else:
                append_flowable(heading_flowables)
            
        elif tok.type == 'paragraph_open':
            if not state.in_list and not state.in_table:
                i += 1
                inline_tok = tokens[i]
                text = process_inline_tokens(inline_tok)
                append_flowable(handle_text_with_math(text, styles['CustomNormal']))
                
        elif tok.type == 'html_block':
            if '<img ' in tok.content and 'data:image/' in tok.content:
                append_flowable(split_xml_and_images(tok.content, styles['CustomNormal']))
                
        elif tok.type == 'bullet_list_open' or tok.type == 'ordered_list_open':
            state.in_list = True
            state.list_items = []
            
        elif tok.type == 'list_item_open':
            i += 1 # p_open
            i += 1 # inline
            text = process_inline_tokens(tokens[i])
            item_flowables = handle_text_with_math(text, styles['CustomNormal'])
            state.list_items.append(ListItem(item_flowables, leftIndent=15))
            
        elif tok.type == 'bullet_list_close' or tok.type == 'ordered_list_close':
            state.in_list = False
            if state.list_items:
                # Fix Bullet Rendering: proper unicode bullet, spacing, and left indent
                append_flowable(ListFlowable(state.list_items, bulletType='bullet', start='\u2022', color=TEXT_MAIN, leftIndent=12, spaceBefore=4, spaceAfter=8))
            append_flowable(Spacer(1, 4))
            
        elif tok.type == 'table_open':
            state.in_table = True
            state.table_data = []
            
        elif tok.type == 'tr_open':
            state.row_data = []
            
        elif tok.type == 'th_open' or tok.type == 'td_open':
            i += 1 # inline
            text = process_inline_tokens(tokens[i])
            state.row_data.append(Paragraph(text, styles['CustomNormal']))
            
        elif tok.type == 'tr_close':
            state.table_data.append(state.row_data)
            
        elif tok.type == 'table_close':
            state.in_table = False
            if state.table_data:
                # Fix Markdown Parsing (Tables): Add proper borders, padding, and alternate row backgrounds
                t = Table(state.table_data, repeatRows=1, style=[
                    ('BACKGROUND', (0,0), (-1,0), NEBULA_GOLD),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('LEFTPADDING', (0,0), (-1,-1), 8),
                    ('RIGHTPADDING', (0,0), (-1,-1), 8),
                    ('GRID', (0,0), (-1,-1), 1, COSMIC_BLUE),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")])
                ])
                append_flowable(t)
                append_flowable(Spacer(1, 12))
                
        elif tok.type == 'blockquote_open':
            bq_flowables = []
            i += 1
            while i < len(tokens) and tokens[i].type != 'blockquote_close':
                if tokens[i].type == 'paragraph_open':
                    i += 1
                    text = process_inline_tokens(tokens[i])
                    bq_style = ParagraphStyle(name='BQ', parent=styles['CustomNormal'], leftIndent=0, textColor=TEXT_MAIN)
                    bq_flowables.extend(handle_text_with_math(text, bq_style))
                i += 1
                
            # Blockquotes become a reusable styled component box
            t = Table([[bq_flowables]], colWidths=[doc.width])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), GLASS_BG),
                ('BOX', (0,0), (-1,-1), 1, COSMIC_BLUE),
                ('TOPPADDING', (0,0), (-1,-1), 12),
                ('BOTTOMPADDING', (0,0), (-1,-1), 12),
                ('LEFTPADDING', (0,0), (-1,-1), 16),
                ('RIGHTPADDING', (0,0), (-1,-1), 16),
            ]))
            append_flowable(t)
            append_flowable(Spacer(1, 10))

        i += 1

    flush_component() # Flush any remaining buffered component
    
    doc.build(flowables, onFirstPage=header_footer, onLaterPages=header_footer)
    pdf_buffer.seek(0)
    
    # Cleanup temp files
    import os
    for tmp in state.temp_files:
        try:
            if os.path.exists(tmp):
                os.remove(tmp)
        except Exception:
            pass
            
    return pdf_buffer
