import io
from io import BytesIO
from markdown_it import MarkdownIt
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib import colors
import matplotlib.pyplot as plt
import re

# Colors from Curious Horizons Design Language
NEBULA_GOLD = colors.HexColor("#dcb44e")
COSMIC_BLUE = colors.HexColor("#1e3a8a")
GLASS_BG = colors.HexColor("#f8fafc")
TEXT_MAIN = colors.HexColor("#111827")
TEXT_MUTED = colors.HexColor("#6b7280")
TEXT_LIGHT = colors.HexColor("#9ca3af")

md = MarkdownIt("commonmark")
plt.switch_backend('Agg')

def render_math_to_image(latex_str, is_display=False):
    fig = plt.figure(figsize=(0.01, 0.01))
    fontsize = 16 if is_display else 12
    try:
        fig.text(0, 0, f"${latex_str}$", fontsize=fontsize)
        buf = BytesIO()
        fig.savefig(buf, format='png', bbox_inches='tight', pad_inches=0.05, dpi=150, transparent=True)
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception as e:
        print("Failed to render math:", latex_str, e)
        plt.close(fig)
        return None

def extract_math(text):
    parts = []
    pattern = r'(\$\$[^\$]+\$\$|\$[^\$]+\$)'
    tokens = re.split(pattern, text)
    for token in tokens:
        if token.startswith('$$') and token.endswith('$$'):
            parts.append(('display_math', token[2:-2]))
        elif token.startswith('$') and token.endswith('$'):
            parts.append(('inline_math', token[1:-1]))
        else:
            if token:
                parts.append(('text', token))
    return parts

def header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('Helvetica-Bold', 10)
    canvas.setFillColor(NEBULA_GOLD)
    canvas.drawString(doc.leftMargin, doc.pagesize[1] - 0.5 * inch, "Curious Horizons")
    
    # Header Divider
    canvas.setStrokeColor(COSMIC_BLUE)
    canvas.setLineWidth(0.5)
    canvas.line(doc.leftMargin, doc.pagesize[1] - 0.55 * inch, doc.pagesize[0] - doc.rightMargin, doc.pagesize[1] - 0.55 * inch)
    
    # Footer Divider
    canvas.line(doc.leftMargin, 0.65 * inch, doc.pagesize[0] - doc.rightMargin, 0.65 * inch)
    
    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(doc.leftMargin, 0.45 * inch, "Generated by Curious Horizons")
    
    # Page Number
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.45 * inch, f"{doc.page}")
    
    canvas.restoreState()

def create_pdf_from_markdown(markdown_text, topic_name="Generated Notes", document_type="PDF Notes"):
    pdf_buffer = BytesIO()
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=1 * inch,
        leftMargin=1 * inch,
        topMargin=1.2 * inch,
        bottomMargin=1.2 * inch
    )
    
    styles = getSampleStyleSheet()
    
    # Base Styles
    styles.add(ParagraphStyle(name='CustomNormal', parent=styles['Normal'], fontSize=11, leading=16, spaceAfter=8, textColor=TEXT_MAIN))
    styles.add(ParagraphStyle(name='CustomHeading1', parent=styles['Heading1'], fontSize=20, leading=24, spaceAfter=12, keepWithNext=True, textColor=NEBULA_GOLD))
    styles.add(ParagraphStyle(name='CustomHeading2', parent=styles['Heading2'], fontSize=16, leading=20, spaceAfter=10, keepWithNext=True, textColor=COSMIC_BLUE))
    styles.add(ParagraphStyle(name='CustomHeading3', parent=styles['Heading3'], fontSize=14, leading=18, spaceAfter=8, keepWithNext=True, textColor=TEXT_MAIN))
    
    # Title Page Styles
    styles.add(ParagraphStyle(name='TitleTopic', parent=styles['Normal'], fontSize=28, leading=34, spaceAfter=8, textColor=NEBULA_GOLD, fontName='Helvetica-Bold'))
    styles.add(ParagraphStyle(name='TitleType', parent=styles['Normal'], fontSize=16, leading=20, spaceAfter=24, textColor=TEXT_LIGHT, fontName='Helvetica'))
    styles.add(ParagraphStyle(name='TitleGen', parent=styles['Normal'], fontSize=11, leading=16, spaceAfter=48, textColor=TEXT_MUTED, fontName='Helvetica'))
    
    flowables = []
    
    # Improved Document Hierarchy (Title Page)
    flowables.append(Spacer(1, 1 * inch))
    flowables.append(Paragraph(topic_name, styles['TitleTopic']))
    flowables.append(Paragraph(document_type, styles['TitleType']))
    flowables.append(Paragraph("Generated by Curious Horizons", styles['TitleGen']))
    flowables.append(Spacer(1, 0.5 * inch))
    
    tokens = md.parse(markdown_text)
    
    class RenderState:
        def __init__(self):
            self.list_items = []
            self.in_list = False
            self.table_data = []
            self.in_table = False
            self.row_data = []
            self.buffering_component = False
            self.component_flowables = []

    state = RenderState()
    
    def append_flowable(f):
        if type(f) is list:
            if state.buffering_component:
                state.component_flowables.extend(f)
            else:
                flowables.extend(f)
        else:
            if state.buffering_component:
                state.component_flowables.append(f)
            else:
                flowables.append(f)

    def flush_component():
        if state.buffering_component and state.component_flowables:
            t = Table([[state.component_flowables]], colWidths=[doc.width])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), GLASS_BG),
                ('BOX', (0,0), (-1,-1), 1, COSMIC_BLUE),
                ('TOPPADDING', (0,0), (-1,-1), 16),
                ('BOTTOMPADDING', (0,0), (-1,-1), 16),
                ('LEFTPADDING', (0,0), (-1,-1), 20),
                ('RIGHTPADDING', (0,0), (-1,-1), 20),
            ]))
            flowables.append(t)
            flowables.append(Spacer(1, 15))
        state.buffering_component = False
        state.component_flowables = []

    def is_component_heading(text):
        text = text.lower()
        return any(k in text for k in ['formula', 'exam trap', 'memory', 'quick revision', 'checklist'])

    def process_inline_tokens(token):
        if not token.children:
            return token.content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        xml = ""
        for child in token.children:
            if child.type == 'text':
                xml += child.content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            elif child.type == 'strong_open':
                xml += "<b>"
            elif child.type == 'strong_close':
                xml += "</b>"
            elif child.type == 'em_open':
                xml += "<i>"
            elif child.type == 'em_close':
                xml += "</i>"
            elif child.type == 'code_inline':
                xml += f"<font name='Courier'>{child.content}</font>"
            elif child.type == 'softbreak':
                xml += " "
            elif child.type == 'hardbreak':
                xml += "<br/>"
        return xml

    def handle_text_with_math(xml_text, style):
        parts = extract_math(xml_text)
        if len(parts) == 1 and parts[0][0] == 'text':
            return [Paragraph(parts[0][1], style)]
            
        import base64
        from PIL import Image as PILImage
        
        paragraph_xml = ""
        for p_type, content in parts:
            if p_type == 'text':
                paragraph_xml += content
            elif p_type == 'inline_math':
                buf = render_math_to_image(content, is_display=False)
                if buf:
                    img_b64 = base64.b64encode(buf.read()).decode('utf-8')
                    buf.seek(0)
                    with PILImage.open(buf) as pil_img:
                        w, h = pil_img.size
                    w_pt = w * 0.75
                    h_pt = h * 0.75
                    paragraph_xml += f'<img src="data:image/png;base64,{img_b64}" width="{w_pt}" height="{h_pt}" valign="middle"/>'
                else:
                    paragraph_xml += f"${content}$"
            elif p_type == 'display_math':
                buf = render_math_to_image(content, is_display=True)
                if buf:
                    img_b64 = base64.b64encode(buf.read()).decode('utf-8')
                    buf.seek(0)
                    with PILImage.open(buf) as pil_img:
                        w, h = pil_img.size
                    w_pt = w * 0.75
                    h_pt = h * 0.75
                    paragraph_xml += f'<br/><img src="data:image/png;base64,{img_b64}" width="{w_pt}" height="{h_pt}"/><br/>'
                else:
                    paragraph_xml += f"<br/>$${content}$$<br/>"
        
        return [Paragraph(paragraph_xml, style)]

    i = 0
    while i < len(tokens):
        tok = tokens[i]
        
        if tok.type == 'heading_open':
            level = int(tok.tag[1])
            if level <= 2:
                flush_component()
                
            style_name = f'CustomHeading{level}' if level <= 3 else 'CustomHeading3'
            i += 1
            inline_tok = tokens[i]
            text = process_inline_tokens(inline_tok)
            heading_flowables = handle_text_with_math(text, styles[style_name])
            
            if level == 2 and is_component_heading(text):
                state.buffering_component = True
                append_flowable(heading_flowables)
            else:
                append_flowable(heading_flowables)
            
        elif tok.type == 'paragraph_open':
            if not state.in_list and not state.in_table:
                i += 1
                inline_tok = tokens[i]
                text = process_inline_tokens(inline_tok)
                append_flowable(handle_text_with_math(text, styles['CustomNormal']))
                
        elif tok.type == 'bullet_list_open' or tok.type == 'ordered_list_open':
            state.in_list = True
            state.list_items = []
            
        elif tok.type == 'list_item_open':
            i += 1 # p_open
            i += 1 # inline
            text = process_inline_tokens(tokens[i])
            item_flowables = handle_text_with_math(text, styles['CustomNormal'])
            state.list_items.append(ListItem(item_flowables, leftIndent=15))
            
        elif tok.type == 'bullet_list_close' or tok.type == 'ordered_list_close':
            state.in_list = False
            append_flowable(ListFlowable(state.list_items, bulletType='bullet', start='bulletcolor', color=TEXT_MAIN))
            append_flowable(Spacer(1, 10))
            
        elif tok.type == 'table_open':
            state.in_table = True
            state.table_data = []
            
        elif tok.type == 'tr_open':
            state.row_data = []
            
        elif tok.type == 'th_open' or tok.type == 'td_open':
            i += 1 # inline
            text = process_inline_tokens(tokens[i])
            state.row_data.append(Paragraph(text, styles['CustomNormal']))
            
        elif tok.type == 'tr_close':
            state.table_data.append(state.row_data)
            
        elif tok.type == 'table_close':
            state.in_table = False
            if state.table_data:
                # Comparison Tables - Styled with Nebula Gold and Cosmic Blue
                t = Table(state.table_data, repeatRows=1, style=[
                    ('BACKGROUND', (0,0), (-1,0), NEBULA_GOLD),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                    ('BOTTOMPADDING', (0,0), (-1,0), 12),
                    ('TOPPADDING', (0,0), (-1,0), 12),
                    ('BACKGROUND', (0,1), (-1,-1), colors.white),
                    ('GRID', (0,0), (-1,-1), 1, COSMIC_BLUE),
                    ('VALIGN', (0,0), (-1,-1), 'TOP')
                ])
                append_flowable(t)
                append_flowable(Spacer(1, 15))
                
        elif tok.type == 'blockquote_open':
            bq_flowables = []
            i += 1
            while i < len(tokens) and tokens[i].type != 'blockquote_close':
                if tokens[i].type == 'paragraph_open':
                    i += 1
                    text = process_inline_tokens(tokens[i])
                    bq_style = ParagraphStyle(name='BQ', parent=styles['CustomNormal'], leftIndent=0, textColor=TEXT_MAIN)
                    bq_flowables.extend(handle_text_with_math(text, bq_style))
                i += 1
                
            # Blockquotes become a reusable styled component box
            t = Table([[bq_flowables]], colWidths=[doc.width])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), GLASS_BG),
                ('BOX', (0,0), (-1,-1), 1, COSMIC_BLUE),
                ('TOPPADDING', (0,0), (-1,-1), 12),
                ('BOTTOMPADDING', (0,0), (-1,-1), 12),
                ('LEFTPADDING', (0,0), (-1,-1), 16),
                ('RIGHTPADDING', (0,0), (-1,-1), 16),
            ]))
            append_flowable(t)
            append_flowable(Spacer(1, 10))

        i += 1

    flush_component() # Flush any remaining buffered component
    
    doc.build(flowables, onFirstPage=header_footer, onLaterPages=header_footer)
    pdf_buffer.seek(0)
    return pdf_buffer
